### ISSUE TITLE
Diff in smart contracts repo is broken

### ISSUE THREAD

**Issue by mationorato** [lambdaclass/era-contracts#17]
Fix the diff not showing in https://github.com/matter-labs/era-contracts/pull/200

**Comment by mationorato** [comment]
One comment: this was caused because the branch did not started from main becuase we needed some specific changes in one specific commit.

I would try to check if it can be redone from main nowadays.

**Comment by ilitteri** [comment]
Fixed in https://github.com/matter-labs/era-contracts/pull/216
